import os
import glob
import pandas as pd
from snakemake.utils import min_version

min_version('5.26.1')

configfile: '../config/hpcnode.yaml'

# Samples and chromosomes as list
SAMPLES = pd.read_table(config['samples'], sep=',')['plantID'].tolist()
CHROMOSOMES = pd.read_table(config['chromosomes'], header=None).iloc[:,0].tolist()

# Reference genome
REFERENCE_GENOME = config['files']['reference_genome']
GFF_FILE = config['files']['gff']

# Paths for output files
TMPDIR = config['temp_dir']
RAW_READ_DIR = '{0}/raw_data'.format(config['raw_read_prefix'])
TRIMMED_READ_DIR = '{0}/trimmed_reads'.format(config['raw_read_prefix'])
QC_DIR = '{0}/qc'.format(config['results_prefix'])
SPECIES_ID_DIR = '{0}/species_id'.format(config['results_prefix'])
BAM_DIR = '{0}/bam'.format(config['results_prefix'])
PROGRAM_RESOURCE_DIR = '{0}/program_resources'.format(config['results_prefix'])
ANGSD_DIR = '{0}/angsd'.format(config['results_prefix'])
NGSLD_DIR = '{0}/ngsld'.format(config['results_prefix'])
POP_STRUC_DIR = '{0}/population_structure'.format(config['results_prefix'])
SS_SFS_DIR = '{0}/single_sample_sfs'.format(config['results_prefix'])
FIGURES_DIR = '{0}/figures'.format(config['results_prefix'])

# Parameters
CORES_PER_NODE = config['cluster']['cores_per_node']
NT_DB_FILE = ['%02d' % x for x in range(0, config['species_id']['num_nt_db_files'])]
NT_DB_FILE_EXT = ['nhd', 'nhi', 'nhr', 'nhn', 'nnd', 'nni', 'nog', 'nsq', 'tar.gz.md5']
NT_DB_FINAL_EXT = ['nal', 'ndb', 'nos', 'not', 'ntf', 'nto']

wildcard_constraints:
    chrom='|'.join([x for x in CHROMOSOMES])

localrules: create_tmp_dir, create_bam_list_allSamples, create_bam_list_forSpeciesID, concat_angsd_stats, create_pos_file_for_ngsLD, concat_sfs, sum_sfs, convert_sites_for_angsd, split_angsd_sites_byChrom, angsd_index_sites, files_for_angsd_site_subset, subset_angsd_gl, subset_angsd_maf, extract_sample_angsd, angsd_done, chloroplast_gene_fasta, index_chloroplast_gene_vcf, concat_fasta, download_nt_database, single_sample_sfs_done

include: 'rules/common.smk'

#raw_read_dict = create_raw_read_dict(RAW_READ_DIR, SAMPLES)

rule all:
   input:
        # Trimming, mapping, and QC
        #'{0}/multiqc/multiqc_report.html'.format(QC_DIR),
        #'{0}/species_id.done'.format(SPECIES_ID_DIR),
        #'{0}/single_sample_sfs.done'.format(SS_SFS_DIR),
        #'{0}/species_id.done'.format(SPECIES_ID_DIR), 
        # Freebayes
        #'{0}/freebayes.done'.format(FREEBAYES_DIR),
        # Angsd
        '{0}/angsd.done'.format(ANGSD_DIR),
        # Population structure
        #expand('{0}/pcangsd/allSamples_{{site}}_maf{{maf}}_pcangsd.{{ext}}'.format(POP_STRUC_DIR), site=['4fold', '0fold'], ext=['cov', 'admix.Q.npy'], maf=['0.05']),
        #expand('{0}/ngsadmix/K{{k}}/allSamples_ngsadmix_{{site}}_maf{{maf}}_K{{k}}_seed{{seed}}.fopt.gz'.format(POP_STRUC_DIR), k=NGSADMIX_K, seed=NGSADMIX_SEEDS, site=['4fold'], maf=['0.05']),
        # Param tests
        #expand('{0}/test_params/GL{{GL}}_baq{{baq}}/CM019112.1_allSamples_allSites_GL{{GL}}_baq{{baq}}.saf.{{ext}}'.format(ANGSD_DIR), chrom=CHROMOSOMES, ext=['gz','idx','pos.gz'], GL=['1','2'], baq=['0','1','2'])
        # NGSLD
        #expand('{0}/pruned/{{chrom}}/{{chrom}}_withMaf{{maf}}_pruned.id'.format(NGSLD_DIR), chrom=CHROMOSOMES, maf=['0.05']),

rule create_tmp_dir:
    output: directory(TMPDIR)
    shell: 'mkdir {output}'

include: 'rules/ref.smk'
include: 'rules/trimming.smk'
include: 'rules/mapping.smk'
include: 'rules/qc.smk'
include: 'rules/species_id.smk'
include: 'rules/single_sample_sfs.smk'
include: 'rules/param_tests.smk'
include: 'rules/angsd.smk'
include: 'rules/population_structure.smk'

rule clean:
    params:
        'logs {0} {1}/* {2} fastp.json'.format(config['results_prefix'], TRIMMED_READ_DIR, TMPDIR)
    shell:
        'rm -rfv {params}'
