import os
import glob
import pandas as pd
from snakemake.utils import min_version

min_version("5.26.1")

#container: "continuumio/miniconda3:4.9.1"

configfile: "../config/config.yaml"

SAMPLES = pd.read_table(config['samples'])['Sample'].tolist()
RAW_READ_DIR = config['paths']['raw_reads']
TRIMMED_READ_DIR = config['paths']['trimmed_reads']
TMPDIR = config['paths']['temp_dir']

REFERENCE_GENOME = config['files']['reference_genome']

RAW_READ_FASTQC_DIR = '../results/qc/fastqc_raw_reads'
TRIMMED_READ_FASTQC_DIR = '../results/qc/fastqc_trimmed_reads'

include: "rules/common.smk"
    
rule all:
    input:
        fastqc_target_files(),
        expand(['{0}/{{sample}}/{{sample}}_trimmed_1.{{ext}}'.format(TRIMMED_READ_FASTQC_DIR), 
                '{0}/{{sample}}/{{sample}}_trimmed_2.{{ext}}'.format(TRIMMED_READ_FASTQC_DIR)],
                sample=SAMPLES, ext=['_fastqc.html', '_fastqc.zip']),
        expand('{trimmed_read_dir}/{sample}/{sample}_{read}.fq.gz', trimmed_read_dir=TRIMMED_READ_DIR, sample=SAMPLES, read=['trimmed_1', 'trimmed_2', 'unpaired']),
        expand('../results/fastp_trim_reports/{sample}_fastp.html', sample=SAMPLES),
        expand('../results/bams/unpaired/{sample}_unpaired_sorted.bam', sample=SAMPLES),
        expand('../results/bams/paired/{sample}_paired_sorted.bam', sample=SAMPLES),
        expand('../results/bams/merged/{sample}_merged_sorted.bam', sample=SAMPLES),
        expand('../results/bams/final/{sample}_merged_sorted_dupsMarked.bam', sample=SAMPLES),
        expand('../results/bams/final/{sample}_merged_sorted_dupsMarked.bai', sample=SAMPLES)

include: "rules/qc_raw_reads.smk"
include: "rules/trim_reads.smk"
include: "rules/qc_trimmed_reads.smk"
include: "rules/mapping.smk"

rule clean:
    params:
        "logs ../results {0}/* {1}/*".format(TRIMMED_READ_DIR, TMPDIR)
    shell:
        "rm -rfv {params}"
